---
- hosts: "{{ hosts_prompt }}"
  gather_facts: no
  connection: ssh

  vars_prompt:
   - name: "hosts_prompt"
     prompt: "Enter the IP / Group Name to run with this Playbook"
     private: no

   - name: "disk_name" 
     prompt: "Enter Path of the Disk used for creating partition"
     private: no

   - name: "pvs_name"
     prompt: "Complete Path and Disk name after creating with partition"
     private: no

   - name: "vg_name" 
     prompt: "Enter Volume Group name to be created:"
     private: no

   - name: "lv_name"
     prompt: "Enter Logical Volume name to be created:"
     private: no

   - name: "file_system" 
     prompt: "Enter the File Systems to Format in:"
     private: no

   - name: "mount_point" 
     prompt: "Where you need to mount it?"
     private: no
   
  tasks:
   - name: Create Partition for "{{ mount_point }}" file system
     remote_user: ansible
     become: yes
     become_method: sudo
     shell:
       /bin/echo -e "n\np\n1\n\n\nt\n8e\nw" | sudo fdisk "{{ disk_name }}" 

   - name: creating volune_group for vg_u01
     remote_user: ansible
     become: yes
     become_method: sudo
     lvg:
       vg: "{{ vg_name }}" 
       pvs: "{{ pvs_name }}"
       pesize: 8

   - name: Creating LVM lv_u01 for "{{ mount_point }}" file system.
     remote_user: ansible
     become: yes
     become_method: sudo
     lvol:
       vg: "{{ vg_name }}"
       lv: "{{ lv_name }}"
       size: 100%FREE 

   - name: Creating the file system on created Logical volume for "{{ mount_point }}".
     remote_user: ansible
     become: yes
     become_method: sudo
     filesystem:
       fstype: "{{ file_system }}"
       dev: "/dev/mapper/{{ vg_name }}-{{ lv_name }}" 
       
   - name: Mount the created filesystem
     remote_user: ansible
     become: yes
     become_method: sudo
     mount:
       path: "{{ mount_point }}" 
       src: "/dev/mapper/{{ vg_name }}-{{ lv_name }}" 
       fstype: "{{ file_system }}" ## Filesystem type
       opts: rw,noatime,noexec,nodev,nosuid 
       state: mounted

#Credits
# https://www.linuxsysadmins.com/creating-logical-volume-using-ansible/
# https://www.redhat.com/sysadmin/automating-logical-volume-manager
# https://github.com/mrlesmithjr/ansible-manage-lvm/blob/master/playbook.yml